src/main/jython/urls.py
import traceback
from django.conf.urls.defaults import *
from django.http import HttpResponseRedirect
from settings import MEDIA_ROOT, ADMIN_MEDIA_ROOT, ROOT_URL, USE_HTTPS
from django.contrib import admin

admin.autodiscover()

try:
    urlpatterns = patterns(
        '',
        (r'^%smedia/workflows/(?P<path>.*)$' % ROOT_URL, 
         'hydrant.views.hide_workflows'),
        (r'^%smedia/(?P<path>.*)$' % ROOT_URL, 'django.views.static.serve', 
         {'document_root': MEDIA_ROOT, 'show_indexes': True}),
        (r'^%smediaadmin/(?P<path>.*)$' % ROOT_URL, 'django.views.static.serve', 
         {'document_root': ADMIN_MEDIA_ROOT, 'show_indexes': True}),
        (r'^%saccounts/login/$' % ROOT_URL, 'django.contrib.auth.views.login',
         {'template_name': 'login.html', 'SSL':USE_HTTPS}, 'login'),
        (r'^%saccounts/signup/$' % ROOT_URL, 'jython.hydrant.views.signup',
         {'SSL':USE_HTTPS}, 'signup'),
    (r'^%saccounts/logout/$' % ROOT_URL, 'django.contrib.auth.views.logout',
     {'next_page':'/%s' % ROOT_URL}, 'logout'),
        #(r'^%sadmin/' % ROOT_URL, include('django.contrib.admin.urls')),
        (r'^%sadmin/(.*)' % ROOT_URL, admin.site.root),
        #    (r'^%s$' % ROOT_URL, lambda request: HttpResponseRedirect('/%sportal/' % ROOT_URL)),
        url(r'^%sfaq/$' % ROOT_URL, 'django.views.generic.simple.direct_to_template',
            {'template': 'faq.html'}, name='faq'),
        url(r'^%sscreencast/$' % ROOT_URL, 'django.views.generic.simple.direct_to_template',
            {'template': 'screencast.html'}, name='screencast'),
        #    (r'^%sforum/' % ROOT_URL, include('forum.urls')),
        (r'^%s' % ROOT_URL, include('jython.hydrant.urls')),        
    )
except:
    traceback.print_exc()
    raise

src/main/jython/kepler/models.py
from django.db import models
from django.contrib.auth.models import User
import widgets
from workflow.proxy import EntityProxy


class Workflow(models.Model):

    """ Stores the MoML file for a workflow along with associated
    metadata.

    moml_file -- The MoML file,
    name -- The verbose name of the Workflow,
    owner -- The User whom uploaded the Workflow.
    created -- The Date/Time which the Workflow was uploaded.
    public -- Whether the Workflow is publically accessable or not.
    description -- A long description of the Workflow.
    deleted -- True if the workflow should be considered deleted.
    valid_users -- Users who're able to access this Workflow in the case
    that it is not public.
    """

    moml_file = models.FileField(upload_to='workflows', 
                                 verbose_name='Workflow file')
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, related_name="worklow_owner",)
    created = models.DateTimeField('date submitted', auto_now_add=True)
    public = models.BooleanField(default=False)
    description = models.TextField()
    deleted = models.BooleanField(default=False,)
    valid_users = models.ManyToManyField(User, verbose_name='valid users', 
                                         blank=True, 
                                         filter_interface=models.HORIZONTAL, 
                                         related_name='workflow_valid_users')

    def get_parameter(self, id):
        """ Gets a WorkflowParameter object linked to this Workflow.
        """
        return WorkflowParameter.objects.get(workflow=self, property_id=id);

    def get_all_parameters(self):
        """ Returns a list of all WorkflowParameter objects linked to
        this Workflow.
        """
        return WorkflowParameter.objects.filter(workflow=self);

    def get_exposed_parameters(self):
        """ Returns a list of all the WorkflowParameter objects linked
        to this workflow which have expose_to_user equal to True.
        """
        return WorkflowParameter.objects.filter(workflow=self, 
                                                expose_to_user=True);

    def __unicode__(self):
        return unicode(self.name)

    def get_proxy_object(self):
        """ Returns a kepler.workflow.proxy.EntityProxy object which
        proxies this Workflow.
        """
        moml = open(self.get_moml_file_filename(), 'r').read()
        return EntityProxy(moml)

    class Admin:
        list_display = ('name', 'owner', 'created', 'public')
        search_fields = ('name', 'description')
        date_hierarchy = 'created'

    class Search:

        """ Class used by the kepler.portalviewshelper.SearchList class.
        """

        list_display = ('name', 'description')
        search_fields = ('name', 'description')
        sortable = ('name',)

class WorkflowParameter(models.Model):

    """ Refers to an Actor property in a specific Workflow. Provides a
    way to assign a different value to a property without changing the
    original MoML file. Also specifies whether the property should be
    exposed to the user via the job submission form, and provides a
    verbose name and description to display on the form.

    workflow -- The Workflow which this property belongs to.
    property_id -- The unique reference used to access this property in
    the workflow.
    expse_to_user -- True if this property should be shown to the user
    on the job submission form.
    description -- A long description of this property.
    name -- The verbose name for this property.
    value -- The default value for this property.
    type -- The type of property. The type refers to the type of
    component used to present the property. The current supported types
    are: SELECT, INPUT, TEXT, CHECKBOX and FILE.
    """

    workflow = models.ForeignKey(Workflow)
    property_id = models.CharField(max_length=200, editable=False)
    expose_to_user = models.BooleanField()
    description = models.TextField()
    name = models.CharField(max_length=50)
    value = models.CharField(max_length=1000)
    type = models.CharField(max_length=50)

    def __unicode__(self):
        return unicode('parameter "%s" for workflow "%s"' 
                       % (self.name, self.workflow.name))

    class Admin:
        list_display = ('workflow', 'property_id', 'name')

class Job(models.Model):

    """ A Job is a single execution of a Workflow.

    workflow -- The Workflow which was executed for this Job.
    owner -- The User whom submitted this Job.
    status -- The Job's current status.
    submission_date -- The date/time when the Job was submitted.
    start_date -- The date/time when the Job's status changed from
    QUEUED to RUNNING.
    end_date -- The date/time when the Job's status changed from RUNNING
    to either DONE or ERROR.
    name -- An optional name for the Job.
    description -- An optional description for the Job.
    """

    workflow = models.ForeignKey(Workflow)
    owner = models.ForeignKey(User)
    status = models.CharField(max_length=200)
    submission_date = models.DateTimeField(auto_now_add=True)
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)
    name = models.CharField(max_length=200, null=True)
    description = models.TextField(null=True)

    def get_job_inputs(self):
        """ Returns all the JobInput objects associated with this Job.
        """
        return JobInput.objects.filter(job=self)

    def get_job_outputs(self):
        """ Returns all the JobOutput objects associated with this Job.
        """
        return JobOutput.objects.filter(job=self)

    def __unicode__(self):
        if self.status == 'NEW':
            status = 'New'
        elif self.status == 'QUEUED':
            status = 'Queued'
        elif self.status == 'RUNNING':
            status = 'Running'
        elif self.status == 'DONE':
            status = 'Complete'
        elif self.status == 'ERROR':
            status = 'Error'
        else:
            status = 'Unknown'
        if self.name is None or self.name == '':
            return '%s Job' % self.workflow
        else:
            return self.name

    class Admin:
        list_display = ('workflow', 'submission_date', 'start_date',
                        'end_date', 'status', 'owner')
        search_fields = ('workflow__name', 'status',)
        list_filter = ('status',)
        date_hierarchy = 'submission_date'

    class Search:

        """ Class used by the kepler.portalviewshelper.SearchList class.
        """

        list_display = ('name', 'workflow', 'status', 'submission_date',
                        'end_date')
        search_fields = ('workflow__name', 'status', 'name', 'description')
        sortable = ('workflow__name',)

class JobInput(models.Model):

    """ When a Job is submitted, all the inputs that are assigned via
    WorkflowParameter objects are saved as JobInputs. They exist solely
    for record keeping purposes.

    job -- The Job which this belongs to.
    parameter -- the WorkflowParameter which this refers to.
    value -- the value which the WorkflowParameter was set to for the
    Job.
    """

    job = models.ForeignKey(Job)
    parameter = models.ForeignKey(WorkflowParameter)
    value = models.TextField()

    class Admin:
        pass

class JobOutput(models.Model):

    """ As a job runs, some actors may produce output. This output is
    captured via ReplacementActors and stored in a file. A JobOutput is
    a reference to this file with additional metadata.

    job -- The Job which produced this output.
    name -- The name of the output, generally the name of the Actor
    which produced it.
    type -- The type of output.
    file -- The file which holds the output.
    creation_date -- The date/time when the output was created.
    """

    job = models.ForeignKey(Job)
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=50)
    # types:    TEXT
    #           HTML
    #           XML
    #           IMAGE
    #           FILE
    file = models.CharField(max_length=200)
    creation_date = models.DateTimeField(auto_now_add=True)

    class Admin:
        list_display = ('creation_date', 'job', 'name', 'type', 'file')

templates/kepler/actor_div.html
{% load textutils %}
{% if actor %}
<div class="actor notdraggable down_start down_end"  
    style="left: {{ actor.location.x|px_to_em }}em; top: {{ actor.location.y|px_to_em }}em">
  <div style="overflow: auto;">{{ actor.name }}</div>
  <div style="display: table;">
    <div class="smalltd">
      <div class="small">
	{% for ip in actor.inputports %}
        <div class="smalltr">
	  <img alt="" id="{{ ip }}" class="block" src="{{ MEDIA_URL }}/images/single-port.png"/>
	</div>
	{% endfor %}
      </div>
    </div>
    <div class="smalltd">
      {% if editable or actor.composite %}<a href="{{ parameters_url_base }}{{ actor.name }}/">{% endif %}
      {% if actor.composite %}
      <img alt="{{ actor.name }}" style="cursor: pointer;" id="{{ actor.name|replace_spaces }}" class="block" src="{{ MEDIA_URL }}/images/composite.png"/>
      {% else %}
      <img alt="{{ actor.name }}" id="{{ actor.name|replace_spaces }}" class="block" src="{{ MEDIA_URL }}/images/basic-actor.png"/>
      {% endif %}
      {% if editable or actor.composite %}</a>{% endif %}
    </div>
    <div class="smalltd">
      <div class="small">
	{% for ip in actor.outputports %}
        <div class="smalltr">
	  <img alt="" id="{{ ip }}" class="block" src="{{ MEDIA_URL }}/images/single-port.png"/>
	</div>
	{% endfor %}
      </div>
    </div>
  </div>
</div>
{% endif %}

templates/kepler/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
{% load rooturl %}
{% load advanced_messaging %}
{% setup_advanced_messaging %}
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE }}" xml:lang="{{ LANGUAGE_CODE }}">
    <head>
        <title>{% block title %}{{ title|escape }}{% endblock %}</title>
		  {% block links %}
		  <link href="/{% root_url %}media/css/base.css" type="text/css" rel="stylesheet" />
		  <link href="/{% root_url %}media/css/dashboard.css" type="text/css" rel="stylesheet" />
		   <link href="/{% root_url %}media/css/changelist.css" type="text/css" rel="stylesheet" />
           <link href="/{% root_url %}media/css/widgets.css" type="text/css" rel="stylesheet" />
			
			{% endblock %}
        <style type="text/css">
            


            {% block extrastyle %}{% endblock %}
        </style>
        <script type="text/javascript" src="/{% root_url %}admin/jsi18n/"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}js/prototype.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}js/core.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}js/SelectBox.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}js/SelectFilter2.js"></script>
        <script type="text/javascript">
            count = 0
            function append_message(message, klass, url) {
                count += 1;
                message_id = 'message_number_' + count;
                str = '<li id="' + message_id + '" class="' + klass + '">';
                if (url != null) {
                    str += '<a href="' + url + '">' + message + '</a>';
                } else {
                    str += message;
                }
                str += ' <a href="#" onClick="destroy_message(\'' + message_id + '\')">(click here to dismiss)</a></li>';
                $('messagelist').insert(str);
            }
            function destroy_message(id) {
                $(id).remove();
            }

        </script>
        {% block extrahead %}{% endblock %}
        {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
    </head>
{% load i18n %}

<body class="{% block bodyclass %}{% endblock %}" {% block extrabodyparams %}{% endblock %}>
<!-- Container -->
<div id="container">
    <!-- Header -->
    <div id="header">
        <div id="branding">
            {% block branding %}{% endblock %}
        </div>
        <div id="user-tools">
            {% if user.is_authenticated %}
                Welcome <strong>{% if user.first_name %}{{ user.first_name|escape }}{% else %}{{ user.username }}{% endif %}</strong>.
            {% endif %}
            {% block userlinks %}
                {% if user.is_authenticated %}
                    <a href="{% url dashboard %}">Dashboard</a>
                    |
                {% endif %}
                    <a href="{% url workflows %}">Workflows</a>
                    |
                {% if user.is_authenticated %}
                    <a href="{% url jobs %}">Jobs</a>
                    |
                    <a href="{% url notifications %}">Notifications (2)</a>
                    |
                    <a href="{% url logout_view %}">Log out</a>
                {% else %}
                    <a href="{% url login_view %}">Log in</a>
                {% endif %}
            {% endblock %}
        </div>
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
            {% if crumbs %}
        <div id="breadcrumbs">
                <a href="{% url dashboard %}">Dashboard</a>
                {% for crumb in crumbs %}
                    {% ifequal crumb '' %}{% else %}
                        &rsaquo; <a href="{{ crumb.path }}">{{ crumb.name }}</a>
                    {% endifequal %}
                {% endfor %}
                &rsaquo;
            {{ title|escape }}
        </div>
            {% endif %}
    {% endblock %}
    <div id="messagelistblock">
    <ul id="messagelist" class="messagelist"></ul>
    </div>
    <div id="object-tools">
        {% block object-tools %}{% endblock %}
    </div>
    <!-- Content -->
    <div id="content">
        {% block content %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}
    <div id="footer">
        <div class="copywrite">
        Created By Tristan King<br/>
        Copyright © 1995 to 2007, James Cook University. All rights reserved.<br/>
        <a href="http://www.jcu.edu.au/top/jcuprd_013723.html">Terms of use</a> | <a href="http://www.jcu.edu.au/privacy/">Privacy statement</a>
        </div>
        <table class="logos" style="margin-left: auto; margin-right: auto;">
            <tr>
                <!-- td><a href="http://www.jcu.edu.au/"><img src="http://www.jcu.edu.au/idc/groups/public/documents/webgraphics/jcu_banner_logo_07.gif" alt="James Cook University"/></a></td -->
                <td><a href="http://www.djangoproject.com"><img src="{{ MEDIA_URL}}img/logos/django-powered.png" alt="Django"/></a></td>
                <td><a href="http://www.jython.org"><img src="{{ MEDIA_URL }}img/logos/jython-powered.png" alt="Jython"/></a></td>
                <!--td><a href="http://www.python.org"><img src="http://www.python.org/community/logos/python-powered-w-70x28.png" alt="Python"/></a></td-->
                <td><a href="http://www.kepler-project.org"><img src="{{ MEDIA_URL }}img/logos/kepler-powered.png" alt="Kepler"/></a></td>
                <!--td><a href="http://archer.edu.au"><img src="{{ MEDIA_URL }}images/archer.png" alt="Archer"/></a></td-->
            </tr>
        </table>
    </div>
    {% endblock %}

    <!-- END Container -->
    </div>
    <script type="text/javascript">
        <!--

    {% if messages %}
    {% for message in messages %}
    append_message('{{ message.message|escape }}', {% ifequal message.type 'ERROR' %}'bad'{% else %}'good'{% endifequal %});
    {% endfor %}
    {% endif %}
        -->
    </script>
</body>
</html>

templates/kepler/base_site.html
{% extends "kepler/base.html" %}

{% block title %}{{ title|escape }} | Hydrant{% endblock %}

{% block branding %}
<img style="float: left; position: absolute;" src="{{ MEDIA_URL }}img/logos/hydrant.gif" alt="hydrant"/><h1 id="site-name">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url welcome %}">Hydrant</a></h1>
{% endblock %}


{% block content %}
<!--div id="hydrant-logo">
    <img src="{{ MEDIA_URL }}img/logos/hydrant.png" alt="hydrant"/>
</div-->
<h1>Welcome to Hydrant</h1>
<h3>What is this?</h3>
<p>This project is intended to create a Web portal for executing kepler workflows.</p>
<p>The project is currently still in the proof of concept stage</p>
<p>You can log in to play with things using either of the following logins<br/>
Username: designer, Password: test<br/>
Username: scientist, Password: test</p>
<p>The designer user reflects the type of user who is kepler savvy and would be responsible for building and deploying workflows for the scientist. The designer can upload workflows and set up <i>exposed parameters</i>, and other properties relevent to the workflow to make it easy for scientists to use.</p>
<p>The scientist user reflects the type of user who just wants to run workflows and doesn't want to have to learn how kepler works or how to use it. The scientist only has access to select and execute avaliable workflows.</p>
<p>Best viewed using <a href="http://www.mozilla.com/en-US/firefox/">Firefox</a> &gt;= 2.0 (i.e. looks terrible, and doesn't work right in other browsers. Compatibility is high on the to-do list)</p>
<p>Development info availiable on the <a href="https://dev.archer.edu.au/projects/kepler/wiki/WebPortal">kepler @ jcu trac</a></p>
{% endblock %}

{% block nav-global %}{% endblock %}

templates/kepler/dashboard.html
{% extends "kepler/base_site.html" %}
{% load rooturl %}

{% block object-tools %}
    {% if user.is_staff %}
    <ul>
        <li style="width: 13em;">
            <a href="{% url upload_workflow %}" class="addlink">Upload Workflow</a>
        </li>
    </ul>
    {% endif %}
{% endblock %}
{% block content %}
<div class="dashboard-block-container">
    <div>
    <div class="dashboard-block">
        <div class="module">
            <h2>Bookmarked Jobs</h2>
            {% if recent_workflows %}
                {% for workflow in recent_workflows %}
                <p><a class="name" href="{% url workflow_view workflow.pk %}">{{ workflow.name }}</a></p>
                {% endfor %}
            {% else %}
                <p>No Bookmarked Jobs</p>
            {% endif %}
        </div>
        <div class="module">
            <h2>Bookmarked Workflows</h2>
            {% if workflows %}
                {% for workflow in workflows %}
                    <p><a class="name" href="{% url workflow_view workflow.pk %}">{{ workflow.name }}</a></p>
                {% endfor %}
            {% else %}
                <p>No Bookmarked Workflows</p>
            {% endif %}
        </div>
    </div>
    <div class="dashboard-block">
        <div class="module">
            <h2>Recent Jobs</h2>
            {% if jobs %}
                {% for job in jobs %}
                <p><a href="{% url job_details_view job.pk %}">{{ job.workflow.name }}</a><br/><small>submitted: {{ job.submission_date }} &nbsp; status: {{ job.status }}</small></p>
                {% endfor %}
            {% else %}
                <p>You have no Jobs</p>
            {% endif %}
        </div>
    </div>
    <div class="dashboard-block">
        <div class="module">
            <h2>Notifications</h2>
            {% if notifications %}
                {% for note in notifications %}
                     <p><a href="{% url job_view job.pk %}">{{ job.template.name }}</a></p>
                {% endfor %}
                {% else %}
                <p>You have no notifications</p>
            {% endif %}
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/kepler/delete_template_confirmation.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url index_view %}">Home</a> &rsaquo;
    {% if crumbs %}
    {% for crumb in crumbs %}
    <a href="{{ crumb.path }}">{{ crumb.name }}</a> &rsaquo;
    {% endfor %}
    {% endif %}
    Delete Template
</div>
{% endblock %}
{% block content %}
    <p>Are you sure you want to delete the template "{{ template.name }}"?</p>
    <form action="" method="post">
    <div>
    <input type="hidden" name="post" value="yes" />
    <input type="submit" value="{% trans "Yes, I'm sure" %}" />
    </div>
    </form>
{% endblock %}

templates/kepler/index.html
{% extends "kepler/base_site.html" %}
{% load i18n %}
{% block extrahead %}{% endblock %}
{% block bodyclass %}{% endblock %}
{% block breadcrumbs %}{% endblock %}
{% block content %}
<div style="float: left; width: 100%;">

    {% if user.is_authenticated %}
    <ul class="object-tools">
        <li>
            <a href="{% url upload_workflow_view %}" class="addlink">Upload Workflow</a>
        </li>
    </ul>
    {% endif %}

    <div class="module">
    <table summary="{% blocktrans with app.name as name %}Models available in the {{ name }} application.{% endblocktrans %}">
    <caption>{% trans 'Workflows in repository' %}</caption>
    {% if workflow_list %}
        {% for model in workflow_list %}
        <tr>
            <th scope="row"><a href="{{ model.view_url }}">{{ model.name|escape }}</a></th>
            <td><a class="changelink" href="{{ model.view_url }}edit/">Edit</a></td>
            <td><a class="addlink" href="{{ model.view_url }}template/">Template</a></td>
            <td><a class="deletelink" href="{{ model.view_url }}delete/">Delete</a></td>
            <td>{{ model.owner }}</td>
        {% if model.public %}
            <td>{% trans 'Public' %}</a></td>
        {% else %}
            <td>{% trans 'Private' %}</td>
        {% endif %}
        </tr>
        {% endfor %}
    {% else %}
        <th>{% trans "There are no workflows in the repository" %}</th>
        <td></td>
    {% endif %}
    </table>
    </div>

    <!-- TEMPLATING BLOCK -->
    <div class="module">
    <table summary="{% blocktrans with app.name as name %}Models available in the {{ name }} application.{% endblocktrans %}">
    <caption>{% trans 'Available Templates' %}</caption>
    {% if template_list %}
        {% for template in template_list %}
        <tr>
            <th scope="row"><a href="{% url template_view template.id %}">{{ template.name|escape }}</a></th>
            <td><a class="changelink" href="{% url edit_template template.id %}">Edit</a></td>
            <td><a class="deletelink" href="{% url delete_template template.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    {% else %}
        <th>{% trans "There are no templates available" %}</th>
        <td></td>
    {% endif %}
    </table>
    </div>

    <!-- WORKSPACE BLOCK -->
{% if user.is_authenticated %}
    <div class="module">
        <table summary="Workspaces active">
        <caption>{% trans 'Active Workspaces' %}</caption>
        {% if workspace_list %}
            {% for workspace in workspace_list %}
                <tr>
                    <th scope="row"><a href="{% url portal_workspace_view workspace.id %}">{{ workspace.name }}{% if workspace.is_template %} (template){% endif %}</a></th>
                    <td><a class="savelink" href="{% url portal_workspace_view workspace.id %}save/">Save</a></td>
                    <td><a class="deletelink" href="{% url portal_workspace_view workspace.id %}close/">Close</a></td>
                </tr>
            {% endfor %}
        {% else %}
            <th>{% trans "You have no active workspaces" %}</th>
            <td></td>
        {% endif %}
        </table>
        </div>

    <!-- JOB BLOCK -->
     <div class="module">
        <table summary="Jobs">
        <caption>{% trans 'Jobs' %}</caption>
        {% if jobs %}
            {% for job in jobs %}
                <tr>
                    <th scope="row"><a href="{% url job_details_view job.pk %}">{{ job.template.name }}</a></th>
                    <td>{{ job.submission_date }}</td>
                    <td>{{ job.status }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <th>{% trans "You have no jobs" %}</th>
            <td></td>
        {% endif %}
        </table>
        </div>
    </div>

{% endif %}
</div>
{% endblock %}
{% block sidebar %}
<div id="sidebar">
{% include 'kepler/login_sidebar.html' %}
</div>
{% endblock %}

templates/kepler/logout.html
{% extends "kepler/base_site.html" %}

{% block content %}

<p>Cya next time!</p>

<p><a href="{% url login_view %}?next={% url dashboard %}">Log in again</a></p>

{% endblock %}

templates/kepler/parameters_form.html
{% if parameters %}
    <table>{{ parameters }}</table>
{% else %}
    <p>No Parameters</p>
{% endif %}

templates/kepler/save_form.html
{% extends "kepler/base_site.html" %}
{% block extrahead %}{{ block.super }}
{% endblock %}
{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}
{% block bodyclass %}change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
    <a href="{% url index_view %}">Home</a> &rsaquo;
    {% if crumbs %}
    {% for crumb in crumbs %}
    <a href="{{ crumb.path }}">{{ crumb.name }}</a> &rsaquo;
    {% endfor %}
    {% endif %}
    Save {% if is_template %}Template{% else %}Workflow{% endif %}
</div>

{% endif %}{% endblock %}
{% block content %}<div id="content-main">
<form enctype="multipart/form-data" action="" method="post" id="save_workspace_form">{% block form_top %}{% endblock %}
<div>
{% if form.error_dict %}
    <p class="errornote">
    </p>
{% endif %}
    <fieldset class="module aligned {{ bound_field_set.classes }}">
    <div class="form-row" >
    <label for="id_name" class="required">Name:</label>
    <input type="text" id="id_name" class="vTextField" name="name" value="{{ original.name }}" />
    </div>
    <div class="form-row checkbox-row" >
        <input type="checkbox" id="id_public" class="vCheckboxField" name="public" {% if original.public %}checked{% endif %}/>
        <label for="id_public" class="vCheckboxLabel">Make public</label>
        <input type="checkbox" id="id_overwrite" class="vCheckboxField" name="overwrite" {% if not is_template %}checked{% endif %}/>
        <label for="id_overwrite" class="vCheckboxLabel">Overwrite original</label>
    </div>
    </fieldset>
<div class="submit-row">
<input type="submit" value="Save and continue editing" name="_continue"/>
<input type="submit" value="Save and close workspace" class="default" />
</div>
   <script type="text/javascript">document.getElementById("id_name").focus();</script>
</div>
</form></div>
{% endblock %}